  name: Mock web data tester

  on:
    schedule:
      - cron: '*/5 * * * *'
        # Triggers the workflow every day at 3:30 and 5:30 UTC
    workflow_dispatch:

  jobs:
    test_runner:
      runs-on: ubuntu-latest

      steps:
        - name: first-step
          run: echo "Hello World"
