  name: Mock web data tester

  on:
    schedule:
      - cron: '15 6 * * *'
        # Triggers the workflow every day at 6:15 UTC
    workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Python Setup
          uses: actions/setup-python@v3
          with:
            python-version: "3.10.10"

        - name: Create virtual environment
          run: python -m venv venv

        - name: Activate virtual environment
          run: source venv/bin/activate

        - name: Install dependencies
          run: |
            pip install --upgrade pip
            pip install behave

        - name: Run tests
          run: behave
