  name: Browser and api tester

  on:
    schedule:
      - cron: '0 16 1 * 4'
        # Triggers the workflow every day-of-month 1 and on Thursday at 16:00 UTC
    workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Python Setup
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"

        - name: Create virtual environment
          run: python -m venv venv

        - name: Activate virtual environment
          run: source venv/bin/activate

        - name: Install dependencies
          run: |
            pip install --upgrade pip
            pip install behave

        - name: Run tests
          run: behave
